// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBieyyoF9Wkn9U8PxjMdWh2Pb61WB7xo',
    appId: '1:285470800009:web:0728d76fe757cdf7aa2e58',
    messagingSenderId: '285470800009',
    projectId: 'crud-app-d08bc',
    authDomain: 'crud-app-d08bc.firebaseapp.com',
    storageBucket: 'crud-app-d08bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAcfdv2yaacD4Y0yRHbQvPtzGv7sb5LI',
    appId: '1:285470800009:android:74d371ffb293ff68aa2e58',
    messagingSenderId: '285470800009',
    projectId: 'crud-app-d08bc',
    storageBucket: 'crud-app-d08bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIZnkkcEHvWnNSSMyPVMAQ2ArNbeMwEQ',
    appId: '1:285470800009:ios:dccb4d82259bd922aa2e58',
    messagingSenderId: '285470800009',
    projectId: 'crud-app-d08bc',
    storageBucket: 'crud-app-d08bc.appspot.com',
    iosBundleId: 'com.example.kunalBrightInfonet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhIZnkkcEHvWnNSSMyPVMAQ2ArNbeMwEQ',
    appId: '1:285470800009:ios:dccb4d82259bd922aa2e58',
    messagingSenderId: '285470800009',
    projectId: 'crud-app-d08bc',
    storageBucket: 'crud-app-d08bc.appspot.com',
    iosBundleId: 'com.example.kunalBrightInfonet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBieyyoF9Wkn9U8PxjMdWh2Pb61WB7xo',
    appId: '1:285470800009:web:212b60b4e0641f64aa2e58',
    messagingSenderId: '285470800009',
    projectId: 'crud-app-d08bc',
    authDomain: 'crud-app-d08bc.firebaseapp.com',
    storageBucket: 'crud-app-d08bc.appspot.com',
  );
}
